server:
  port: 8001

spring:
  application:
    name: InfoShow8001
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AirportManage?serverTimezone=UTC&amp&useUnicode=true&amp&characterEncoding=utf8
    username: root
    password: 200715

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    preferIpAddress: true